name: React Build

on:
  push:
    paths:
      - '**'
      - .github/workflows/frontend.yml

env:
  AWS_DEFAULT_REGION: us-east-1
  BUCKET_NAME: dragon-zakura-0613
  NODE_ENV: production

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # setup node.js
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Install and Build
      - name: Build
        run: |
          yarn install --production=false
          yarn build
          aws s3 cp dist s3://$BUCKET_NAME/ --recursive
